// Generated by CoffeeScript 1.7.1

/*
	@author: Shawn Eastwood
	@package: seng515-petroleum-explorer
 */

(function() {
  var VisualizationController;

  VisualizationController = (function() {
    function VisualizationController(oil_data, discrete_flag) {
      this.oil_data = oil_data;
      this.discrete_flag = discrete_flag;
    }

    VisualizationController.prototype.getVisualizationMethod = function() {
      if (this.discrete_flag === true) {
        return "discrete";
      } else {
        return "histogram";
      }
    };

    return VisualizationController;

  })();

  (typeof exports !== "undefined" && exports !== null ? exports : window).VisualizationController = VisualizationController;

}).call(this);

//# sourceMappingURL=visualization_controller.map
