// Generated by CoffeeScript 1.7.1
(function () {
	var FullTable;
	/**
	 * @class FullTable
	 * @param SearchController with search results
	 * @param $tableContainer {*|jQuery} object for placeholder for table data
	 */
	FullTable = (function () {
		function FullTable(SearchController, $tableContainer) {
			this.SearchController = SearchController;
			this.$tableContainer = $tableContainer;
			this.displayTable();
			this.listenChanges();
			this.toggleButton = $tableContainer.parent().find("toggle-table").removeAttr("diabled");
			this.listenToggle();
		}

		/**
		 * Display all search results in table container using datatables
		 * @returns {*}
		 */
		FullTable.prototype.displayTable = function () {
			var data;
			console.log("Call to display table");
			console.dir(this.SearchController.resultSet);
			// Check if datatable has already been initialized.  If it is, then exit to avoid error
			if (this.$tableContainer.hasClass(".dataTable") === true) {
				return;
			}
			if (this.SearchController.resultSet.length > 0) {
				data = this.SearchController.resultSet;
				this.$tableContainer.dataTable({
					data:    data,
					columns: [
						{
							data: "H",
							title: "Thickness"
						},
						{
							data: "InstanceId",
							title: "Instance ID"
						},
						{
							data: "KRav",
							title: "Average Hydrocarbon Movability"
						},
						{
							data: "KRc",
							title: "Cumulative Hydrocarbon Movability"
						},
						{
							data: "OID_",
							title: "Object ID"
							// TODO: Not relevant to user.  Consider removing
						},
						{
							data: "PHIR",
							title: "Cumulative Pore Volume"
						},
						{
							data: "PHIc",
							title: "Cumulative Porosity"
						},
						{
							data: "PLOT_SYMBO",
							title: "Plot Symbol" //TODO: Remove displaying
						},
						{
							data: "Pc",
							title: "Effective Yield"
						},
						{
							data: "Pp",
							title: "Peak Value"
						},
						{
							data: "Pt",
							title: "Effective Life Cycle"
						},
						{
							data: "Soc",
							title: "Oil Saturation"
						},
						{
							data: "UWI",
							title: "UWI"
						},
						{
							data: "Vshc",
							title: "Cumulative Shale Content"
						},
						{
							data: "Well_Class",
							title: "Well Class"
						},
						{
							data: "Well_Drill",
							title: "Well Drill"
						},
						{
							data: "Well_Opera",
							title: "Company"
						},
						{
							data: "Well_PoolN",
							title: "Well Pool Name"
						},
						{
							data: "Well_Prima",
							title: "Primary Formation"
						},
						{
							data: "Well_Provi",
							title: "Province"
						},
						{
							data: "Well_Statu",
							title: "Status"
						},
						{
							data: "Well_Uniqu",
							title: "Full UWI"
						},
						{
							data: "Well_WellN",
							title: "Name"
						}
					]
				});
				// For debugging
				return console.log("Attempting to create datatable with data" + this.SearchController.resultSet);
			}
		};

		/**
		 * Toggle table update on `ResultsUpdated` event
		 * @returns {*|jQuery}
		 */
		FullTable.prototype.listenChanges = function () {
			return $("body").on("ResultsUpdated", (function (_this) {
				return function () {
					return _this.displayTable();
				};
			})(this));
		};

		/**
		 * Toggle full table data when clicking the button
		 * @returns {*}
		 */
		FullTable.prototype.listenToggle = function () {
			return this.toggleButton.on("click", (function (_this) {
				return function () {
					return _this.$tableContainer.toggle("slow");
				};
			})(this));
		};

		return FullTable;

	})();

	(typeof exports !== "undefined" && exports !== null ? exports : window).FullTable = FullTable;

}).call(this);
