// Generated by CoffeeScript 1.7.1
(function() {
  var SearchController;

  SearchController = (function() {
    SearchController.NULL_ERROR_MESSAGE = "Could not find data, as it was null";

    function SearchController(data) {
      this.data = data;
    }

    SearchController.prototype.findResults = function() {};

    SearchController.prototype.showTwo = function() {
      return 2;
    };

    return SearchController;

  })();

  (typeof exports !== "undefined" && exports !== null ? exports : window).SearchController = SearchController;

}).call(this);

//# sourceMappingURL=search.map
