// Generated by CoffeeScript 1.7.1
(function() {
  var SearchController, assert, mySearchController;

  assert = require("chai").assert;

  SearchController = require("../../app/scripts/components/search/search.js").SearchController;

  mySearchController = new SearchController();

  describe("Search", function() {
    it("Has a valid search controller", function() {
      return assert.isObject(mySearchController);
    });
    return it("Returns null error message when passed null data", function() {
      var actual, expected, myTestSearchController;
      myTestSearchController = new SearchController(null);
      expected = myTestSearchController.NULL_ERROR_MESSAGE;
      actual = myTestSearchController.findResults();
      return assert.equal(expected, actual);
    });
  });

}).call(this);

//# sourceMappingURL=search_tests.map
