// Generated by CoffeeScript 1.7.1
(function() {
  var MapToolbar;

  MapToolbar = (function() {
    function MapToolbar(toggled, mapToolbar, toolbarToggle, mapToolbarIcon, mapToolbarContent, searchButton) {
      this.toggled = toggled;
      this.mapToolbar = mapToolbar;
      this.toolbarToggle = toolbarToggle;
      this.mapToolbarIcon = mapToolbarIcon;
      this.mapToolbarContent = mapToolbarContent;
      this.searchButton = searchButton;
      this.mapToolbar = $(".mapToolbar");
      this.toolbarToggle = this.mapToolbar.find(".show-toolbar");
      this.mapToolbarIcon = this.toolbarToggle.find("i");
      this.mapToolbarContent = this.mapToolbar.find(".toolbar-content");
      this.searchButton = this.mapToolbar.find(".show-search");
      this.searchForm = this.mapToolbar.find(".search");
      this.initMapToggle();
    }

    MapToolbar.prototype.initMapToggle = function() {
      if (this.toggled === true) {
        return;
      }
      this.toggleMapToolbar();
      return this.toolbarToggle.on("click", (function(_this) {
        return function() {
          return _this.toggleMapToolbar();
        };
      })(this));
    };

    MapToolbar.prototype.toggleMapToolbar = function() {
      this.mapToolbarContent.toggle("slow");
      return this.mapToolbarIcon.toggleClass("icon-expand icon-contract");
    };

    MapToolbar.prototype.initSearchForm = function() {
      return this.searchButton.on("click", (function(_this) {
        return function() {
          return _this.toggleSearchForm();
        };
      })(this));
    };

    MapToolbar.prototype.toggleSearchForm = function() {
      return this.searchForm.toggle("slow");
    };

    return MapToolbar;

  })();

  (typeof exports !== "undefined" && exports !== null ? exports : window).MapToolbar = MapToolbar;

}).call(this);

//# sourceMappingURL=map-toolbar.map
