// Generated by CoffeeScript 1.7.1
(function () {
	$(function () {
		var initMapToggle,
			mapToolbar, mapToolbarButtons, mapToolbarIcon,
			setToggle, toolbarToggle,
			mapToolbarContent, mainAccordion;

		/**
		 * mapToolbarButtons finds all buttons in toolbar-buttons div.
		 * mapToolbarContent finds all the sections elements in sidebar-content-container
		 * these section elements will contain the actual implemented parts of selected function
		 * @type {*|jQuery|HTMLElement}
		 */
		mapToolbar = $(".mapToolbar");
		toolbarToggle = mapToolbar.find(".show-toolbar");
		mapToolbarIcon = toolbarToggle.find("i");
		mapToolbarButtons = mapToolbar.find(".toolbar-buttons button");
		mapToolbarContent = mapToolbar.find(".sidebar-content-container section").hide();
		mapToolbarAccordion = mapToolbar.find("#accordion");
		/**
		 * This function initializes mapToolbarButtons to hidden, and toggles
		 * the contents of the sidebar when called.
		 * @returns {*}
		 */
		initMapToggle = function () {
			mapToolbarButtons.hide();
			return toolbarToggle.on("click", function () {
				mapToolbarButtons.toggle();
				mapToolbarContent.slideUp();
				mapToolbarButtons.removeClass("active");
				return mapToolbarIcon.toggleClass("icon-expand icon-contract");
			});
		};

		/**
		 * This function is called to toggle content for a single toolbar button.
		 * It first hides any active content, and then uses the data-target attribute
		 * of selected button to find and show its corresponding content.
		 * TODO: use jQuery map with an array of jQuery objects for better selector speed
		 * @returns {*}
		 */
		setToggle = function () {
			return mapToolbarButtons.on("click", function () {

				mapToolbarContent.slideUp();
				mapToolbarButtons.removeClass("active");

				var targetSelector = $(this).attr("data-target");
				var target = $("."+targetSelector).slideDown();
				$(this).toggleClass("active");
			});
		};
		mapToolbarAccordion.accordion({
			collapsible: true,
			heightStyle: "content"
		});
		initMapToggle();
		setToggle();

	});

}).call(this);