// Generated by CoffeeScript 1.7.1
(function () {
	$(function () {
		var initMapToggle,
			mapToolbar, mapToolbarButtons, mapToolbarIcon,
			setToggle, toolbarToggle, clearFields,
			mapToolbarContent;

		/**
		 * mapToolbarButtons finds all buttons in toolbar-buttons div.
		 * mapToolbarContent finds all the sections elements in sidebar-content-container
		 * these section elements will contain the actual implemented parts of selected function
		 * @type {*|jQuery|HTMLElement}
		 */
		mapToolbar = $(".mapToolbar");
		/* Making the toolbar visible after everything is loaded.
		 * This avoids having the entire toolbar opened while loading the website.
		 */
		mapToolbar[0].style.display = "inline";

		toolbarToggle = mapToolbar.find(".show-toolbar");
		mapToolbarIcon = toolbarToggle.find("i");
		mapToolbarButtons = mapToolbar.find(".toolbar-buttons button");
		mapToolbarContent = mapToolbar.find(".sidebar-content-container section").hide();
		mapToolbarAccordion = mapToolbar.find("#accordion");

		// Used to clear all the seach input
		mapToolbarClearSearch = mapToolbar.find("#clear-search");
		searchFields =
			[
				mapToolbar.find("#uwi"),
				mapToolbar.find("#lsd"),
				mapToolbar.find("#section"),
				mapToolbar.find("#township"),
				mapToolbar.find("#range"),
				mapToolbar.find("#meridian"),
				mapToolbar.find("#company"),
				mapToolbar.find("#status")
			];

		/**
		 * This function initializes mapToolbarButtons to hidden, and toggles
		 * the contents of the sidebar when called.
		 * @returns {*}
		 */
		initMapToggle = function () {
			mapToolbarButtons.hide();
			var titles = ["Show toolbar", "Hide toolbar"];
			return toolbarToggle.on("click", function () {
				toolbarToggle[0].title = toolbarToggle[0].title === titles[0] ? titles[1] : titles[0];
				mapToolbarButtons.toggle();
				mapToolbarContent.slideUp(400);
				mapToolbarButtons.removeClass("active");
				return mapToolbarIcon.toggleClass("icon-expand icon-contract");
			});
		};

		/**
		 * This function is called to toggle content for a single toolbar button.
		 * It first hides any active content, and then uses the data-target attribute
		 * of selected button to find and show its corresponding content.
		 * TODO: use jQuery map with an array of jQuery objects for better selector speed
		 * @returns {*}
		 */
		setToggle = function () {
			return mapToolbarButtons.on("click", function () {

				mapToolbarButtons.removeClass("active");
				mapToolbarContent.slideUp(400);

				var targetSelector = $(this).attr("data-target");
				var target = $("."+targetSelector).slideDown(400);
				$(this).toggleClass("active");
			});
		};

		/*
		 * Allows the accordion in the search tab to be collapsible.
		 */
		mapToolbarAccordion.accordion({
			collapsible: true,
			heightStyle: "content"
		});

		initMapToggle();
		setToggle();
	});

}).call(this);