// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var callSearch, hideMapContent, initMapToggle, mapToolbar, mapToolbarContent, mapToolbarIcon, searchButton, toolbarToggle;
    mapToolbar = $(".mapToolbar");
    toolbarToggle = mapToolbar.find(".show-toolbar");
    mapToolbarIcon = toolbarToggle.find("i");
    mapToolbarContent = mapToolbar.find(".toolbar-content");
    searchButton = mapToolbar.find(".show-search");
    initMapToggle = function() {
      hideMapContent(mapToolbarContent);
      return toolbarToggle.on("click", function() {
        mapToolbarContent.toggle("slow");
        return mapToolbarIcon.toggleClass("icon-expand icon-contract");
      });
    };
    hideMapContent = function(mapContent) {
      return mapContent.hide();
    };
    callSearch = function() {
      return searchButton.on("click", function(e) {});
    };
    initMapToggle();
    return callSearch();
  });

}).call(this);

//# sourceMappingURL=map-toolbar.map
