// Generated by CoffeeScript 1.7.1
(function() {
  jQuery(document).ready(function() {
    var MapToolbar, SearchController, mapController;
    mapController = new MapController();
    MapToolbar = new MapToolbar();
    return SearchController = new SearchController();
  });

}).call(this);

//# sourceMappingURL=main.map
